Create schema burn_house;
use burn_house;

create table utente(
email varchar(100) primary key ,
password varchar(30) not null,
nome varchar(50) not null,
cognome varchar(50) not null,
unique(nome,cognome),
data_nascita date not null,
tipo varchar(8) not null
);

create table indirizzo(
via varchar(60) not null,
cap char(5) not null,
citta varchar(50) not null,
primary key(via,cap,citta)
);

create table pagamento(
num_carta varchar(20) not null,
utente varchar(100) not null,
primary key(num_carta,utente),
foreign key(utente) references utente(email)
on update cascade
on delete restrict
);

create table produttore(
partita_iva char(11) primary key,
sede varchar(50) not null
);


create table product(
  codice int primary key,
  nome varchar (100) not null,
  prezzo double not null,
  descrizione varchar (1000) not null,
  gradazione float not null,
  tipo varchar (100) not null,
  img varchar(500)
);

create table recensione(
id integer auto_increment not null,
valutazione integer not null,
utente varchar(100) not null,
foreign key(utente) references utente(email)
on update cascade
on delete no action,
prodotto integer not null,
foreign key(prodotto) references product(codice)
on update cascade
on delete restrict,
primary key(id,utente,prodotto)
);


create table ordine(
codice integer auto_increment primary key,
prezzo decimal(4,2) not null,
quantita integer not null,
ind_spedizione varchar(50) not null,
aliquota_IVA integer not null,
utente varchar(100) not null references utente(email) on update cascade on delete no action,
data_effettuazione date not null
);

create table inclusione(
num_ordine integer not null,
prodotto integer not null,
primary key(num_ordine,prodotto),
foreign key(num_ordine) references ordine(codice) on update no action on delete no action,
foreign key(prodotto) references product(codice) on update cascade on delete no action
);

create table produzione(
prodotto integer not null,
produttore char(11) not null,
primary key(prodotto,produttore),
foreign key(prodotto) references product(codice) on update cascade on delete no action,
foreign key(produttore)references produttore(partita_IVA) on update cascade on delete no action
);


create table spedizione(
utente varchar(100) not null references utente(email) on update cascade on delete no action,
via varchar(60) not null,
cap char(5) not null,
citta varchar(50) not null,
foreign key(via,cap,citta) references indirizzo(via,cap,citta) on update cascade on delete no action,
primary key(utente,via,cap,citta)
);




INSERT INTO product values (1,"ACQUAVITE D'UVA RAU",25.00,"Acquavite d'uva della Linea Sol porta in se tutto l'aroma intenso ed unico dell'isola antica. Il clima mite e gli ampi spazi sono, infatti, l'ambiente ideale per la coltivazione dei vigneti e dei frutteti, dai quali provengono le materie prime. Il gusto è dolce e profondo, ricco di aromi intensi con sentori floreali. Ricorda il profumo dell'uva appena raccolta. Distillato di uve Moscato e Malvasia.",42,"distillato","1.jpg");
INSERT INTO product values (2,"AMARO CYNAR CL 70",14.00,"Cynar è un liquore ottenuto dall’infusione di 13 tipi diversi di erbe e piante, tra cui la cinaria, estratta dal carciofo e rinomata per le sue elevate proprietà digestive. Si tratta di un prodotto ricco di profumi e la sua gradazione alcolica contenuta lo rende accessibile ad un vasto pubblico; un prodotto che, come recitava un celebre spot pubblicitario, è “contro il logorio della vita moderna”. Genuino e amichevole è l’amaro perfetto per il dopo pasto e può essere degustato liscio o con ghiaccio. Per dargli una veste più accattivante, può essere abbinato a dell’acqua tonica o consumato con una spruzzata di seltz, in un bicchiere fresco e, magari, con una fettina di arancia. Insomma, davvero tanti utilizzi per un prodotto esclusivo e tutto italiano.",16.5,"liquore","2.jpg");
INSERT INTO product values (3,"THE BALVENIE DOUBLEWOOD WHISKY 12 ANNI",69.90,"Morbido e dolce dai sapori meravigliosamente combinati: la dolcezza delle nocciole, la speziatura della cannella e uno strato di sherry delicatamente proporzionato. Deve il suo carattere distintivo alla maturazione in due diversi tipi di legno. Ciascun passaggio conferisce qualità diverse al whisky single malt. Le botti tradizionali ammorbidiscono e aggiungono un carattere delicato, il legno di sherry, invece, dona profondità e pienezza di sapore e gli ultimi mesi in queste botti permettono ai whisky di sposarsi armoniosamente. ",40,"distillato","3.jpg");
INSERT INTO product values (4,"GINO BARILE GRAPPA 21 ANNI",153.90,"Segue un lungo corso d’invecchiamento di oltre due decenni (1991-2012), per arrivare a mostrarsi in tutta la sua complessità aromatica e in tutta la sua generosità gustativa. Questa Grappa 21 anni “Gino Barile” - Grappa Barile non trova facilmente eguali. Di qualità insuperabile, è a dir poco eccellente.Ambrata intensa alla vista, con riflessi aranciati. Di largo respiro il bouquet olfattivo, composto da sentori di frutta sotto spirito, profumi di erbe aromatiche e di cuoio. Al palato è secca, appena tannica e avvolta da complessi aromi, che chiudono su note legnose e di liquirizia.",49,"distillato","4.jpg");
INSERT INTO product values (5,"CAPOVILLA ALBICOCCHE DEL VESUVIO",95.00,"Vittorio Gianni Capovilla è ampiamente riconosciuto come uno dei migliori distillatori al mondo. Posseduto da una passione irragionevole per la frutta, questo anziano meccanico si è messo alla ricerca delle varietà più rare e più sorprendenti attraverso le Alpi e l'Italia o ancora in Francia e in Romania. Questo distillato restituisce l'albicocca matura in modo sublime, cosa che non le impedisce di amoreggiare con gli agrumi (bergamotto, verdello).",49,"distillato","5.jpg");
INSERT INTO product values (6,"CHINA MARTINI CL 70",12.58,"La China Martini è un amaro italiano prodotto con la corteccia del “China Calissaia” e da una miscela di erbe ed essenze aromatiche che le conferiscono un calda sensualità. L'estratto della corteccia, contenente oltre venti principi attivi noti per le loro proprieta toniche, conferisce a China Martini una personalita decisa. E’ un liquore dall’inconfondibile gusto dolce-amaro. Colore bruno ambrato intenso, aroma con note agrumate, seguite da sensazioni floreali e balsamiche dovute a essenze e a legni aromatici.",25,"liquore","6.jpg");
INSERT INTO product values (7,"COGNAC REMY MARTIN VSOP CL 70",12.90,"Colore giallo dorato pallido e luminoso. Al naso esprime sensazioni dolci di uva passa e vaniglia, insieme a note di burro fuso e nocciola, floreale di rosa gialla, lievi toni agrumati e di ribes bianco oltre a sentori di mandorla. Al palato risulta morbido ed equilibrato, avvolgente e presente nei numerosi ritorni aromatici, in un rincorrersi di uva passa e pasta frolla, quasi una percezione di pasticceria verso l’infinita persistenza ammandorlata.",40,"distillato","7.jpg");
INSERT INTO product values (8,"INDONESIAN LONG PEPPER SNAPS",45.00,"Un incrocio tra esotico e tradizionale, ecco come inquadrare l'Acquavite “Long Pepper Snaps” della Copenhagen Distillery. Di solito la “Snaps” si consuma abitualmente liscia durante i pasti, in accompagnamento a piatti di pesce. Qui abbiamo un distillato dall'insolito sentore di pepe lungo indonesiano, un aroma di bocca dolce e una piccantezza delicata e persistente... da acquolina in bocca. Perfetta trasparenza e luminosità per questa Snaps danese. Al naso si esprime con note speziate di pepe lungo e freschi sentori piccanti, accenni di vaniglia. Al palato è fresca, di corpo, inedita. Persistente e piacevole regala una sensazione di curioso formicolio.",41,"distillato","8.jpg");
INSERT INTO product values (9,"CORBEZZOLO",13.17,"Il Liquore di Corbezzolo Sardegna  è un liquore tipico sardo prodotto utilizzando le bacche del corbezzolo del Gennargentu, pianta molto comune nell’Isola. Il liquore conserva pienamente tutti gli aromi e i profumi particolarissimi della vegetazione spontanea della macchia mediterranea e gli sprigiona con dolcezza e delicatezza. È un liquore dal sapore piacevole e dolce, apprezzabile anche dai palati che prediligono gusti lievi. Si ottiene grazie all’infusione a freddo, per un periodo di tempo che varia dai 15 ai 25 giorni. La particolarità è nella totale assenza di zucchero, ma nell’utilizzo di piccole quantità di miele.",25,"liquore","9.jpg");
INSERT INTO product values (10,"CREMA DI MIRTO RAU",12.50,"Un’esclusiva ricetta che racchiude in sè il piacevole aroma (dolce e amaro) delle bacche di mirto raccolte in Sardegna e la delicata fragranza della crema di latte.  Il territorio di tutta làisola si caratterizza di una fitta vegetazione spontanea fatta di cespugli di mirto, una pianta dalle foglie profumate che produce delle bacche da cui poi ha origine questo gustoso liquore da fine pasto. Ottimo bevuto liscio, nei cocktails o per accompagnare gustosi gelati. Per assaporare al meglio le sue caratteristiche si consiglia di consumarlo fresco.",17,"liquore","10.jpg");
INSERT INTO product values (11,"EL TARASCO GRAN RESERVA CHARANDA",39.90,"Le condizioni meteorologiche dello stato del Michoacan in Messico, hanno consentito nei secoli una grande produzione di canna da zucchero. Dalla fermentazione e distillazione di questa pianta tropicale e dei suoi derivati, come il roano e il piloncillo, nasce una delle bevande tradizionali del Messico: il Charanda. El Tarasco è un blend di Rum invecchiati tra i 18 e i 24 mesi in botti ex-Whisky americane ed ex-Sherry. La distillazione, invece, avviene principalmente in un alambicco di rame con una piccola percentuale in colonna. Il Tarasco Gran Reserva Charanda è estremamente morbido, con note dolci di vaniglia e liquirizia, mentre il finale è piacevolmente piccante.",40,"distillato","11.jpg");
INSERT INTO product values (12,"THE MACALLAN SHERRY OAK CASK 12 ANNI",125.00,"Macallan 12 Y.O. Sherry Oak Cask è un single malt scotch whisky composto unicamente da whisky affinati in botti di rovere rosso spagnolo. Le botti maturano vino sherry per almeno due anni prima di essere impiegate per l'affinamento del whisky. E' un whisky dove la dolcezza della vaniglia del legno si lega alla spezia della rovere europea lasciando spazio a un finale lungo e vellutato. Si presenta fresco e dolce, con note di fiori di melo, frutta tropicale e sfumature di sherry.",40,"distillato","12.jpg");
INSERT INTO product values (13,"FILUFERRU '926 RAU",12.90,"Tipica acquavite ottenuto dalla distillazione delle vinacce sarde selezionate, dal gusto intenso e carico. Le vinacce, sottoprodotto del processo di vinificazione, vengono stoccate e poi trasportate presso la distilleria, dove unite a vini vengono sottoposte al processo di doppia distillazione con appositi alambicchi. Il corpo del distillato, che costituisce la bevanda, viene conservato in botti di rovere e sottoposto ad un periodo di stagionatura di 1 anno. Questa acquavita, si distingue per il suo vigore, stemperato dalla leggera e caratteristica aromatizzazione data dai semi di finocchio selvatico.",42,"distillato","13.jpg");
INSERT INTO product values (14,"FONTANA ITALIA",39.90,"Fontana Italia è un pisco prodotto partendo da un vitigno di origine italiana, che si coltiva nelle zone di Moquegua e Tacna. La fermentazione naturale senza lieviti aggiunti dura tra 5 e 10 giorni. La marcerazione sulle bucce è di 48 ore. La distillazione avviene in tre alambicchi di rame da 300 e 400 litri. Il distillato esce dall’alambicco a 41-43% ABV e viene lasciato riposare per due anni in tini d’acciaio inossidabile, quindi imbottigliato a still proof. Lo consigliamo in un Pisco Punch, drink ufficiale di San Francisco: 6 cl Pisco Puro, 3 cl acqua naturale, 2 cl sciroppo di zucchero all ananas, 2 cl succo di lime, 2 cl polpa d ananas.",40,"distillato","14.jpg");
INSERT INTO product values (15,"GIN GENESI",34.90,"Genesi è ottenuto dalla distillazione in un piccolo alambicco in rame di 14 botaniche selezionate, tra cui le bacche selvatiche di ginepro e mirto, cresciute spontaneamente lungo le coste della Sardegna e raccolte a mano. Il Ginepro viene raccolto in Gallura, da piante che crescono selvatiche vicino al mare. La sensazione balsamica è data principalmente dalle bacche di mirto, raccolte a mano da piante spontanee, che conferiscono anche delicate note di frutti rossi. L’aroma speziato e floreale è dato da alcune specie officinali tipiche della Sardegna:L’Elicriso, il Timo, il Rosmarino, la Lavanda. La nota fruttata è conferita dagli aromi che maturano sotto il sole della Sardegna.",42,"distillato","15.jpg");
INSERT INTO product values (16,"GRAPPA BARRIQUE RAU",7.60,"La grappa barricata, è un’armoniosa unione di grappe di mono-vitigno lasciate maturare in preziose barrique di rovere francese, lasciando libera la grappa di estrarre dal legno un colore naturale e un carattere pieno ed elegante. Il lungo riposo dona a questo distillato finezza, pienezza e le conferisce il caratteristico colore ambrato. Il profumo di frutta suggerisce l’aroma di una pesca matura e dell’albicocca, su una complessa trama speziata di fondo che proviene dal contatto prolungato con il legno. In bocca è morbida, vellutata e dotata di ottimo equilibrio. Chiude in una lunga persistenza.",37.5,"distillato","16.jpg");
INSERT INTO product values (17,"GRAPPA DI VERMENTINO RAU",7.30,"Grappa di Vermentino della Linea Sol porta in se tutto l'aroma intenso ed unico dell'isola antica. Il clima mite e gli ampi spazi sono, infatti, l'ambiente ideale per la coltivazione dei vigneti e dei frutteti, dai quali provengono le materie prime. La cura nella lavorazione, con piccoli alambicchi in rame discontinui in bagnomaria a vapore, valorizza il delicato profumo dei vitigni della Sardegna, legati al peculiare microclima delle colline e dei venti ricchi di salsedine. Dolce e delicato, il gusto esprime note floreali, di frutta matura e miele, ricco di aromi intensi. Distillato di uve Vermentino.",40,"distillato","17.jpg");
INSERT INTO product values (18,"JUNE ESPIRIT DISTILLATO DI VINACCE",21.30,"June Espirit è un innovativo distillato di vinacce in cui sono stati messi in infusione fiori di vite raccolti in giugno (da Ugni Blanc e Merlot) e ridistillato in un alambicco fiorentino, utilizzato tipicamente per la preparazione dei profumi. Questo liquore floreale prende il nome dal mese in cui sbociano i fiori usati per prepararlo, i petali vengono infusi con acquavite d'uva neutra prima di essere distillati in un alambicco. I distillati separati vengono quindi miscelati insieme e distillati nuovamente per ottenere quello che è il prodotto finale.",28,"distillato","18.jpg");
INSERT INTO product values (19,"LIMONCELLO RAU",9.80,"Al gusto fresco e delicatamente fruttato, questo liquore racchiude in sé tutto l'aroma degli agrumi maturati sotto il sole di Sardegna. Un liquore cremoso, rotondo, avvolgente, dall'aroma intenso ed inebriante. Si tratta di un liquore dolce, dal caratteristico colore giallo, che si ottiene lasciando macerare nell’alcool puro le scorze di limone con l’aggiunta di uno sciroppo a base di acqua e zucchero. il liquore colpisce subito l’olfatto per la fragranza degli aromi della scorza di limone veicolati dalle note eteree dell’alcol. L’assaggio è morbido, equilibrato e dolce. Da bere liscio, con ghiaccio o direttamente dal frigorifero, ottimo se accompagnato da un gelato o una macedonia; nessuno può resistere al suo gusto tipicamente italiano.",24,"liquore","19.jpg");
INSERT INTO product values (20,"LIQUIRIZIA JOIA PURA RAU",7.00,"Questo delicato liquore nasce dalla sapiente infusione della radice di liquirizia in purissimo alcool e racchiude in se il profumo e la genuinità di questa pianta Mediterranea.Si caratterizza per purezza, eleganza, grande personalità e per l'inconfondibile gusto fine e delicato. Eccellente come aperitivo, ottimo come dopo pasto, da bere freddo, ben si presta per essere impiegato nella preparazione di originali cocktails. Il gusto unico e avvolgente esprimono appieno le caratteristiche della materia prima, e il delicato ma persistente aroma esprime tutta la sua forza.",21,"liquore","20.jpg");
INSERT INTO product values (21,"TALISKER SKYE",37.90,"Prodotto nell’unica distilleria presente sull’Isola di Skye, questo Single Malt è noto a tutti per l’intenso aroma di torba e per il suo caratteristico gusto quasi salino, peculiarità apprezzate dai veri intenditori ma che mettono alla prova chi ci si accosta per la prima volta. Caratteristiche che stanno a sottolineare il legame ineluttabile che c’è tra questo particolare whisky, l’ambiente e il mare che circonda l’isola e gli uomini che la abitano e che lo lavorano. Proposto dalla Talisker stessa come sostituto del 10 anni, questo single malt è creato dal blend di distillati da botti selezionate, di diversi stili ed età, rivisitazione di un grande classico che racchiude in sè forza ed eleganza. Color oro antico brillante, sorprende l’olfatto con l’iniziale e violento aroma di torba, per poi cedere a seguire note di agrumi canditi, pepe, caramello, frutta secca, malto, zenzero e sfumature salmastre.",45.80,"distillato","21.jpg");
INSERT INTO product values (22,"MING RIVER SICHUAN BAIJIU",32.00,"Il Baijiu è il nuovo distillato di tendenza proveniente dalla Cina, distillato principalmente dal sorgo rosso, anche se spesso sono utilizzati anche altri tipi di cereale quali frumento, orzo o miglio. Viene prodotto con fermentazione lunga e spontanea, con lieviti autoctoni per due mesi, che produce intensi aromi di ananas e frutta esotica matura. Viene distillato in un alambicco discontinuo Pot Still tradizionale cinese. L'invecchiamento, di circa due anni, avviene in contenitori di ceramica e/o acciaio. Da gustare liscio come prevede la tradizione in piccoli bicchieri di vetro o ceramica. Da provare anche in cocktail con ginger beer o succhi di frutta esotica come mango, ananas e maracuja.",45,"distillato","22.jpg");
INSERT INTO product values (23,"PECORA NERA LIQUIRIZIA",13.00,"Liquore di liquirizia nato per stupire, pronto a farsi notare e ricordare. Una bottiglia subito riconoscibile per un liquore davvero unico, nato dalla sapiente infusione della radice di liquirizia in alcol purissimo, con un processo che racchiude e preserva profumi e genuinità. La liquirizia, ingrediente base di questo liquore, è particolarmente indicata a fine pasto, preferibilmente servita fredda. Non contiene alcun tipo di colorante e conservante. A differenza di altri liquori a base di liquirizia, Pecora Nera ha una marcia in più, data dall'uso di aromi e estratti naturali durante il processo di preparazione, per rendere l'infuso quanto più gradevole possibile allàolfatto",22,"liquore","23.jpg");
INSERT INTO product values (24,"QUEIROLO ACHOLADO PISCO",22.00,"Un Pisco prodotto a partire da un blend di uva Italia, Quebranta, Negra Criolla e Moscatel. La fermentazione avviene con lieviti naturali a temperatura controllata intorno ai 22°C, la distillazione è in alambicchi alla francese del tipo Charentais e il riposo avviene in contenitori di acciaio inox per evitare qualsiasi possibilità di agente esterno contaminante. Al palato predominano gli aromi di fiori bianchi, fichi e prugne secche. Ideale da bere puro o in miscelazione, perfetto per il Pisco Sour. Nel 1877 la famiglia Queirolo partì da Genova per arrivare in Perù e si stabilì nel quartiere storico di Pueblo Libre, a Lima, dove fondò nel 1880 la Cantina Queirolo.",42,"distillato","24.jpg");
INSERT INTO product values (25,"VELVET DISARONNO CL 100",18.50,"Liquore cremoso e vellutato. Al naso spicca la vaniglia bourbon, sentori di marzapane e mandorle. Il gusto è vellutato, liscio, nocciolato, leggermente amaro. Disaronno Velvet dovrebbe essere gustato esclusivamente con ghiaccio per esaltare pienamente il suo gusto unico e fresco. Si presenta nella bottiglia iconica con tappo quadrato, ma stavolta vestita di bianco per un liquore vellutato, dal sapore intenso e unico, perfetto per chi ama i liquori alla crema dal gusto deciso, che unisce il classico carattere distintivo di Disaronno con indimenticabili note vellutate. Il palato è morbido, delicato, con una consistenza simile al velluto e una lunga persistenza in chiusura.",17,"liquore","25.jpg");
INSERT INTO product values (26,"LE CUPOLE TENUTA TRINORO 2019",33.00,"Il secondo vino di Tenuta di Trinoro, Le Cupole, è stato prodotto per la prima volta nel 1995. L’assemblaggio dei quattro vitigni, Merlot, Cabernet Franc, Cabernet Sauvignon e Petit Verdot cambia ogni anno nel rispetto dell’annata. Il vino è esuberante, ricco di frutta matura e brillante, tannini estratti e presenta un colore ricco. Vino di grande eleganza, colore rubino, vivace e intenso, al naso si apre con note di frutto maturo, ciliegia e marasca, prugna, ginepro, pepe in grani, tocchi vegetali, rosa e polvere pirica poi spezie. Al palato è vivace, asciutto, caldo, con un tannino di nerbo e un frutto piacevole sul finale, morbido e lungo, centrato nell’equilibrio e riccamente fruttato, con buon apporto fresco-sapido.",14,"vino","26.jpg");
INSERT INTO product values (27,"LE STANZE DEL POLIZIANO 2017",45.00,"Un grande rosso moderno, al quale è stato dato il nome Le Stanze, titolo di un’insigne opera del poeta Angelo Ambrogini. Le Stanze di Poliziano spicca per eleganza nel panorama enologico della Toscana. Si tratta di un vino rosso di stile internazionale, ottenuto da taglio bordolese di Cabernet Sauvignon e Merlot, affinato per 16 mesi in barrique nuove. È intenso, corposo, morbido e persistente, dai tannini levigati e setosi. Di color rosso rubino, al naso esprime belle note di ciliegia, di amarena, di spezie orientali. Al palato è fresco, avvolgente, caratterizzato da una trama tannica di impeccabile tessitura. Di buona persistenza. A tutto pasto, si abbina a ricchi piatti di cacciagione tipici della zona di Montepulciano.",14.5,"vino","27.jpg");
INSERT INTO product values (28,"'POGGIO ALLE NANE' JEROBOAM LE MORTELLE ANTINORI 2020",73.30,"Nato dall’unione delle migliori uve di Cabernet Franc, Cabernet Sauvignon ed una piccola quota di Carménère con il terroir unico dei vigneti di Poggio alle Nane, una delle aree più vocate dell’azienda e capace di produrre uve di straordinaria qualità. Un vino dalla grande complessità aromatica e dall’elegante fitta trama tannica. La classe e la personalità dei questo vino si impongono già all’olfatto con aromi di grande complessità che delicatamente ma incessantemente affiorano e si moltiplicano. Al gusto il vino è equilibratamente austero e potente con un finale molto persistente e tannini aristocratici",14,"vino","28.jpg");
INSERT INTO product values (29,"QUATER VITIS ROSSO FIRRIATO 2015",16.90,"I quattro Cru del Quater Vitis Rosso esprimono tutta le personalità di altrettante varietà autoctone siciliane in un percorso di vinificazione singolo e differente, per poi unirsi armonicamente, dopo minuziosi assaggi che certificano il giusto livello di maturazione, in un unico vino. Quater Vitis Rosso è prodotto utilizzando le migliori uve dell’anno di Nero d’Avola, Perricone, Frappato provenienti dai vigneti di Pianoro Cuddìa e Nerello Cappuccio, proveniente dalla tenuta di Cavanera Etnea. Queste varietà vengono allevate con pratiche agronomiche diversificate per vitigno, così come diversi sono i tempi di raccolta delle uve, che viene completata entro la metà del mese di settembre per i vitigni di Frappato, Perricone e Nero d’Avola, nel mese di Ottobre, per il vitigno di Nerello Cappuccio.",14,"vino","29.jpg");
INSERT INTO product values (30,"RUNGG TRAMIN 2018",16.00,"Il Merlot Cabernet della Cantina Tramin viene prodotto nella zona collinare dei Ronchi (Rungg) sul versante sud di Termeno particolarmente soleggiato. È un taglio bordolese che nasce dalla splendida unione di uve Merlot, Cabernet Sauvignon e Franc. I profumi sono di notevole vigore e piacevolezza, di frutta rossa e spezie. In bocca rivela bella eleganza, sapidità e freschezza. Questo vino altoatesino si presenta alla vista di colore rosso rubino brillante.  Il sorso si distende corposo e strutturato, la trama tannica è morbida ed equilibrata. Finale lungo e persistente. Si sposa con i secondi piatti di carne rossa: arrosto, selvaggina, brasato. Ottimo anche con i formaggi stagionati.",13,"vino","30.jpg");
INSERT INTO product values (31,"AMÈ MOSCATO DI SARDEGNA DOC 2022",19.00,"Vino dolce giovane, fresco, ottimo per accompagnare formaggi erborinati leggermente piccanti o dolci della tradizione sarda. Colore giallo dorato intenso. Al naso evidenti sensazioni morbide di albicocca appassita, fichi, miele, frutta candita e piccoli fiori bianchi. In bocca si percepisce la setosità e morbidezza tipiche del vitigno, arricchite da un spalla acida e minerale. Buon bilanciamento di zuccheri, acidità, alcool. Il finale è lungo, caldo, e ricorda gli agrumi canditi, cannella, frutta a polpa bianca.",17.5,"vino","31.jpg");
INSERT INTO product values (32,"ARENU VERMENTINO DI SARDEGNA DOC 2020",10.80,"Ottimo come aperitivo, è il naturale accompagnamento di prodotti del mare. Profumo delicato, con toni floreali e vegetali di macchia mediterranea e note di frutti estivi. Si tratta di un vino bianco a Denominazione di Origine Controllata, ottenuto da uve Vermentino. Vino dal colore paglierino, intenso, luminoso e caldo. Consistente e con un profumo delicato, con toni floreali e vegetali di macchia mediterranea e note di frutti estivi. AL palato le tipiche note varietali di morbidezza del vitigno vengono bilanciate da viva freschezza e mineralità.",12,"vino","32.jpg");
INSERT INTO product values (33,"ASSOLO CANNONAU DI SARDEGNA DOC 2021",12.00,"Un Cannonau elegante: vino rosso Cannonau Assolo della Tenuta L'Ariosa. Nell’entroterra idilliaco e incontaminato dell’isola mediterranea della Sardegna, la Tenuta L’Ariosa ha trovato il suo posto. Dal colore rosso rubino intenso con un unghia violacea; ha un profumo fresco, speziato, con note di confettura di mora e piccoli frutti rossi. Al gusto è ricco, con tannini eleganti, piacevole struttura e corpo, di lunga persistenza. Questo gusto vellutato con note speziate, ed il finale lungo lo rendono perfetto per accompagnar primi piatti ricchi con sughi di carne, arrosti di carne rossa, pecorini stagionati, verdure fritte.",14,"vino","33.jpg");
INSERT INTO product values (34,"BAROLO CASTELLO DI VERDUNO 2019",37.50,"Il Barolo di Castello di Verduno è un vino elegante e austero dall’ottimo rapporto qualità/prezzo, vinificato in tini di rovere aperti e affinato per 31 mesi in grandi botti. Dal colore luminoso, rosso rubino brillante. Il sorso è strutturato, intenso e piacevolmente tannico, sostenuto da una sottile freschezza. Dal profumo ampio e balsamico, questa elegante miscela di frutta e spezie contiene note di:  pepe, confettura, ciliegia sotto spirito, timo, geranio, violetta. In bocca domina la freschezza con una finale lungo ed equilibrato",14,"vino","34.jpg");
INSERT INTO product values (35,"BOLGHERI ROSSO LE COLONNE DIEVOLE 2018",17.00,"Il vino Bolgheri DOC Tenuta Le Colonne è un vino rosso equilibrato e armonico che nasce dalla selezione delle migliori uve di Cabernet Franc, Merlot e Cabernet Sauvignon. L’estrema vicinanza dei vigneti di Tenuta Le Colonne al mare permette di esaltare al meglio tutte le magnifiche qualità di questo blend di uve. Di uno stupendo color rosso con particolari riflessi granata. Il naso è di quelli importanti: Frutti rossi, maturi. Confettura di fragole, ribes e altri piccoli frutti di bosco. Al palato la sensazione è quella di trovarci al cospetto di un rosso importante. Caldo, avvolgente, intenso. Il tannino è ben integrato grazie anche alla sosta in botte grande, ma presenta alcune piccole imperfezioni che andranno a risolversi col tempo. Il finale lungo e persistente, caratteristica ben presente in questi uvaggi, scivola via su note fruttate e minerali.",13.5,"vino","35.jpg");
INSERT INTO product values (36,"BRUNELLO DI MONTALCINO MASTROJANNI 2011",65.00,"Brunello di Montalcino D.O.C.G. della Vigna Schiena d’Asino, un solo ettaro di viti anziane e nobilissimo. Si affina fino a 55 mesi prima di scoprire il suo vero volto di rubino, di porpora e granato. È ricco e solido, ma non pesante. I tannini viziano con la loro eleganza e costringono all’attenzione. Vino potente, caldo e austero che fa sentire la terra, profuma di spezie e di frutta e come le spezie e la frutta attacca volentieri la carne al rosso, i formaggi duri, l’aspra cacciagione. Di colore rosso rubino scuro,qualche nota tra il boschivo ed il fungino. Si avvertono profumi di fiori appassiti e note rugginose. In bocca è severo, preciso nello svolgimento e ben articolato fino alla terrosa e lunga persistenza.",13.5,"vino","36.jpg");
INSERT INTO product values (37,"CHIANTI CLASSICO SAN JACOPO VICCHIOMAGGIO 2018",9.90,"Il “San Jacopo” Castello di Vicchiomaggio è senza alcun dubbio una delle etichette che meglio rappresenta il vino più tipico del territorio chiantigiano. È una vera e propria icona della storia di questo splendido angolo della Toscana, compreso tra le città d’arte di Firenze e Siena. Nel calice si presenta con una veste color rosso rubino luminoso con riflessi brillanti. All'olfatto regala intensi profumi di ciliegia matura, di amarena, di frutti di bosco, sfumature di violetta, di erbe aromatiche della macchia mediterranea e di delicate spezie. Al palato è di medio corpo, con tannini sottili e un frutto succoso ed espressivo, che accompagna verso un finale piacevolmente fresco e sapido. Il Sangiovese nella sua espressione più limpida e classica.",13,"vino","37.jpg");
INSERT INTO product values (38,"BOLGHERI ROSSO 'CAMPO AL MARE' FOLONARI 2020",15.99,"Blend di uve internazionali Merlot, Cabernet Sauvignon, Cabernet Franc e Petit Verdot provenienti dalle parcelle produttive della Tenuta, Campo al Mare si distingue per il suo stile inconfondibile. Grande morbidezza ed una trasversale capacità di abbinamento. Rosso porpora brillante e vivace, l’annata 2021 si apre al naso con descrittori floreali, di frutta rossa, erbe aromatiche ed eleganti note speziate di cioccolato al latte e vaniglia. Al palato è croccante, con tannini setosi dilavanti ma mai spigolosi, ed un finale di piacevole armonia vinosa.",14,"vino","38.jpg");
INSERT INTO product values (39,"GALATEA VERMENTINO DI SARDEGNA DOC 2021",15.70,"Ottenuto da uve in tarda vendemmia, è un Vermentino carico di aromi e intensi sapori. Colore paglierino con riflessi verdognoli, intenso, luminoso e caldo. Profumo delicato, con toni floreali e vegetali di macchia mediterranea e note di frutti estivi. Al palato note varietali, morbidezza del vitigno vengono bilanciate da viva freschezza e mineralità. Si abbina particolarmente con prodotti del mare, piatti leggeri a base di carni bianche e formaggi di media stagionatura. A caratterizzare questo vino sono i frutti estivi e le delicate note aspre che rilascia.",11.5,"vino","39.jpg");
INSERT INTO product values (40,"I SIMBOLI VERMENTINO DI SARDEGNA DOC 2020",14.00,"'I simboli vermentino' prodotto dalla cantina Tenuta l'Ariosa, è un vino prodotto da uve in purezza di Vermentino, uva simbolo della Sardegna. Ad un esame visivo si presenta con un colre giallo scarico con alcuni riflessi verdognoli che tendono a scomparire con il tempo, al naso piacevoli note fruttate di melone bianco, di agrumi quale il cedro, il bergamotto e il limone, al palato di buon corpo e persistenza, molto delicato e fine. Un vino da bere come aperitivo, o accompagnando piatti di pesce o carni bianche.",12,"vino","40.jpg");
INSERT INTO product values (41,"LAGREIN FRANZ HAAS 2018",13.00,"Piena e ricca espressione di vino rosso dell'Alto Adige. Il Lagrein si presenta con un colore rosso profondo ed intenso che in alcune annate tocca note violacee. Il suo bouquet è molto intenso e ampio, spaziando dai frutti rossi maturi alle violette, dalle note speziate all’erba fresca e al cacao. Al palato il vino seduce con la sua personalità decisa, i tannini massicci e vellutati, la gradevole pienezza e una nota finale lunga ed avvolgente. Il vino può essere bevuto giovane, comunque un periodo più lungo di affinamento in bottiglia lo rende più morbido e rotondo.",12.5,"vino","41.jpg");
INSERT INTO product values (42,"L'ENCANTADA 1976 DOMAINE LE SABLE ARMAGNAC",133,"Estremamente gradevole da sorseggiare a fine pasto, magari in accompagnamento a un buon sigaro. Questo Bas Armagnac, prodotto da Domane le Sable, è stato imbottigliato allo stato naturale, senza riduzione del grado alcolico. Matura in botti di rovere, dimostra di avere un bell’equilibrio e di essere caratterizzato da una fine e una grande eleganza.",40,"distillato","42.jpg");
INSERT INTO product values (43,"CHATEAU LA CROIX ST.VINCENT POMEROL 2019",55,"Lo Château La Croix St. Vincent nasce in vigneti situati nella parte sud dell’altopiano di Pomerol. È prodotto principalmente con uve Merlot e con un taglio di cabernet franc, raccolte e selezionate interamente a mano. Dopo fermentazione tradizionale in acciaio per 14-16 settimane a temperatura controllata, il vino affina per 11-15 mesi in botti di rovere parzialmente nuove, prima di essere immesso in commercio. Presenta un colore rosso rubino intenso; al naso si apre con eleganti profumi di frutti a bacca rossa, infine al palato risulta complesso e morbido, con tannini maturi",13.5,"vino","43.jpg");
INSERT INTO product values (44,"MONTECUCCO ROSSO LE QUERCIOLE 2018",9.90,"Il Montecucco 'Le Querciole' è un vino di colore rosso rubino intenso, quasi impenetrabile. Le sfumature tendono al granato. Al naso emergono i frutti rossi maturi, la ciliegia, la mora, la prugna. Quindi accenni balsamici che lasciano il posto a nette sortite speziate al pepe nero. In bocca risulta pieno e asciutto. Si avverte un discreto tannino ad introdurre un fruttato intenso. Non mancano riferimenti minerali con un finale piuttosto lungo e persistente. Da affiancare a primi con sughi strutturati e secondi di carne. Ottimo con la selvaggina e con i formaggi e i salumi tipici della tradizione toscana.",14,"vino","44.jpg");
INSERT INTO product values (45,"PEDRASTELLA IGT ISOLA DEI NURAGHI 2021",9.00,"Pedrastella è un vino rosso a Indicazione Geografica Tipica, Isola dei Nuraghi, ottenuto da uve autoctone della Sardegna. Vino di colore rosso rubino intenso, brillante, profumi fragranti di piccoli frutti rossi, di confettura di ciliegia e mora, note speziate di pepe e cuoio. Al gusto è morbido, suadente, con tannini eleganti e finale di lunga persistenza, di gran corpo. Accompagna carni rosse, arrosto ed in umido, primi piatti saporiti e piccanti, formaggi stagionati. Servire ad una temperatura di 16'18 °C meglio se ossigenato in caraffa prima del consumo.",14,"vino","45.jpg");
INSERT INTO product values (46,"PINOT NERO CASTELLO DELLA SALA ANTINORI 2016",50.00,"Prodotto dal 1990 esclusivamente da uve Pinot Nero è, in un certo senso, “l’alter ego” del Cervaro: insieme rappresentano le due diverse espressioni dell’anima complessa e raffinata del Castello della Sala. I 4 ettari di vigneto da cui è prodotto sono situati ad oltre 400 metri s.l.m. su suoli calcarei ricchi di fossili con sabbie di origine sedimentaria che risalgono al Pliocene. Di colore rosso granato acceso, al naso ricorda profumi delicati che variano dalle spezie a sentori di viola e di rosa con note di piccoli frutti rossi. Al palato è morbido e sapido, con tannini raffinati, setosi e dolci. Il finale è lungo ed equilibrato, disponibile fin da subito ma con grande potenziale di invecchiamento.",13.5,"vino","46.jpg");
INSERT INTO product values (47,"ROSSO DI MONTEPULCIANO DE RICCI 2020",12.00,"Questo Rosso di Montepulciano si presenta di color rosso rubino ricamato nei profumi su nuance di lamponi e fragoline di bosco, con qualche cenno piccante. Impronta gustativa tendenzialmente dolce, tannino lieve e di raro sapore, per un sorso goloso e immediatamente piacevole. Il vino è prodotto da uve Sangiovese con una piccola aggiunta di Merlot, che vengono parzialmente pigiate, per poi essere vinificate in tini di acciaio a temperatura controllata con una macerazione sulle bucce che dura al massimo di 15 giorni. L'affinamento del vino avviene in tonneaux per ca. 6 mesi, per poi proseguire per almeno 6 mesi in bottiglia.",13,"vino","47.jpg");
INSERT INTO product values (48,"SASS'ANTICO CAGNULARI IGT ISOLA DEI NURAGHI 2019",12.00,"Nasce da un vitigno autoctono della provincia di Sassari, SassàANtico è un vino rosso a Indicazione Geografica Tipica, Isola dei Nuraghi, ottenuto da uve Cagnulari. Vino di colore rosso brillante, limpido. Esprime al naso la sua giovinezza e freschezza con intensi ed eleganti profumi di frutti di bosco e confetture, leggermente speziato. In bocca è intenso, caldo, morbido ed equilibrato con tannini soffici, di gran corpo. Lunga persistenza. Accompagna carni rosse, arrosto ed in unmido, selvaggina, formaggi piccanti e di media e lunga stagionatura. Da servire alla temperatura di 18'20 °C meglio se ossigenato prima del consumo.",12.5,"vino","48.jpg");
INSERT INTO product values (49,"SASSICAIA TENUTA SAN GUIDO 2017",300.00,"Sassicaia è senza dubbio uno dei più celebri vini italiani nel mondo. Proviene da un vigneto di 75 ettari particolarmente vocato, in cui le parcelle presentano caratteristiche differenti, con formazioni calcaree e un alto contenuto sassoso, particolarità da cui deriva probabilmente il toponimo “sassicaia”. L’esposizione dei terreni è ad ovest e sud-ovest. La fermentazione avviene in acciaio, a temperatura controllata, con macerazione sulle bucce di circa 10 giorni. L’affinamento del Bolgheri Sassicaia DOC della Tenuta San Guido si svolge in barrique di rovere francese, per 24 mesi, con successiva sosta in bottiglia. Alla vista, il vino si presenta color rosso rubino intenso. Al naso si esprime su sentori di frutti rossi maturi, frutti di bosco e cola, erbe aromatiche e mandorle tostate. Al palato, il sorso è austero, ricco e compatto. Mostra un corpo sostenuto e buona componente acida.",14,"vino","49.jpg");
INSERT INTO product values (50,"RAINOLDI INFERNO RISERVA VALTELLINA SUPERIORE 2018",28.00,"Inferno Riserva di Rainoldi Vini è un vino rosso prodotto con uva Nebbiolo nel comune di Chiuro in provincia di Sondrio. Fa parte della Linea Riserva dell’Azienda. Lo trovate su Vinodalproduttore.it al prezzo consigliato da Rainoldi Vini. Le uve dell’Inferno vengono vendemmiate durante la seconda decade di ottobre. A seguito di un’accurata selezione dei grappoli e una pigio-diraspatura soffice avviene la fermentazione con macerazione a temperatura controllata. Il vino subisce un lungo affinamento in barriques nuove di rovere francese e successivamente in bottiglia. Al naso il profumo è fine e complesso, con note di tabacco su fondo di prugne e terra bagnata. Al palato si presenta intenso e persistente in cui il finale è lungo e l’acidità è bilanciata da una polpa vigorosa.",13.5,"vino","50.jpg");
INSERT INTO product values (51,"TRAMINER AROMATICO FRIULI DOC 2020",17.90,"Il Traminer è indubbiamente uno dei vini bianchi più conosciuti e apprezzati in Italia, grazie al suo profilo aromatico particolarmente intenso e fruttato. Si tratta di un vino elegante e raffinato, caratterizzato da un bouquet olfattivo complesso, aromatico e potente che abbinato alla consistenza del vino rende il Traminer un prodotto d'eccellenza e da un gusto fresco e piacevolmente sapido. I sentori tipici sono fruttati (maracuja, ananas, pesca), speziati (chiodi di garofano) e floreali (rosa). Si abbina con formaggi saporiti, pesce e crostacei.",12.5,"vino","51.jpg");
INSERT INTO product values (52,"CHARDONNAY CONTESSA ENTELLINA DOC CHIARANDÀ 2015",32.90,"Ambizioso per carattere e struttura, il “Chiarandà” rappresenta quanto di meglio lo chardonnay è in grado di esprimere nell’ampia zona della Sicilia Occidentale. Vinificato in acciaio e lasciato maturare in barrique e tonneaux, il Contessa Entellina Chardonnay DOC “Chiarandà” di Donnafugata è vino di personalità ed eleganza, capace di unire tutta la potenza e la mediterraneità siciliana con la soavità tipica del vitigno. Ottimo anche oggi, è vino che migliorerà con il passare degli anni. Di colore giallo paglierino, al naso esprime un bellissimo profilo olfattivo composto da note di frutta a polpa gialla, pesca ed albicocca, di vaniglia e di burro. In bocca è rotondo, avvolgente, strutturato e di buon equilibrio grazie ad una buona componente acida. Chiude con un bel finale, di ottima persistenza.",13.5,"vino","52.jpg");
INSERT INTO product values (53,"GEWURZTRAMINER 2019",22.90,"Gewurztraminer di Yarden: un vino bianco che conquista con il suo profilo aromatico e il suo sapore fresco, ideale per accompagnare aperitivi o cene a base di pesce. Viene prodotto sulle alture di Golan, a quasi 1200 metri di altitudine e ottenuto con uve 100% chardonnay. Il risultato è un vino bianco secco e morbido, caratterizzato da un bouquet aromatico ampio e intenso e da una piacevole acidità finale. Questo vino seducente e inebriante ha unàintensa armonia di aromi e profumi, un tripudio di fiori e frutta tropicale. Nasce dall’omonimo vitigno aromatico a bacca rosa, originario dell’Alto Adige: il nome ‘gewurz’ significa ‘speziato’, mentre Traminer deriva dal nome tedesco di Termeno, affascinante villaggio in provincia di Bolzano.",13.5,"vino","53.jpg");
INSERT INTO product values (54,"MULLER THURGAU 2022",11.90,"Il Müller Thurgau di Colterenzio è un vino unico nel suo genere. Al naso e al palato fiori di sambuco, pesca e noce moscata. Si tratta di un vino leggermente aromatico. Il mosto fermenta a temperatura controllata in fermentino di acciaio e matura alcuni mesi sui lieviti.Il Müller Thurgau è indicato come aperitivo, ideale con frutti di mare leggermente speziati e pesce arrosto. Il Müller Thurgau è un vitigno a bacca bianca dalla storia relativamente recente. Fu creato infatti nel 1882 dall’enologo svizzero Hermann Müller, originario del Canton Turgovia, incrociando le varietà di Riesling Renano e Madeleine Royal durante il suo periodo di insegnamento nella prestigiosa scuola enologica di Geisenheim. A partire dall’inizio del XX secolo si diffuse con crescente successo in tutta la Germania, in Svizzera, in Austria e in Italia, soprattutto in Alto Adige e nella Val di Cembra.",12,"vino","54.jpg");
INSERT INTO product values (55,"ALTO ADIGE RIESLING DOC 2019",13.40,"Il Riesling Alto Adige DOC di Falkenstein è un vino bianco alto atesino prodotto con Riesling Renano e rappresenta il fiore all’occhiello di questa cantina. Le uve vengono coltivate in Val Venosta, fra i 600 e 900 metri di quota, nelle zone alte dei vigneti, dove il Riesling riesce ad esprimere al meglio la sua aromaticità inconfondibile. Questo Riesling ben bilanciato è caratterizzato da sentori fruttati e minerali, ben equilibrati tar di loro. Di colore giallo dorato, al naso sprigiona sentori fruttati di pesca e ananas, con note minerali. Al sorso si conferma fresco e sapido, ben equilibrato con un finale molto lungo e persistente. Si abbina a ricchi primi a base di pasta anche ripiena e secondi a base di carne bianca.",13.5,"vino","55.jpg");
INSERT INTO product values (56,"BIANCO SASSAIA 2021",21.90,"Il 'Sassaia' è un vino bianco agreste e di carattere a base principalmente di uve Garganega, che fermenta con i propri lieviti in botti di rovere e viene imbottigliato senza filtrazioni o chiarificazioni. L'intenso bouquet olfattivo mischia profumi di frutta gialla a cenni minerali e tostati. Il gusto è fresco ed equilibrato, di grande persistenza, attraversato da una piacevole vena minerale. E’ imbottigliato nel mese di agosto dell’anno successivo, senza aggiunta di solfiti. L'intenso aroma e il lungo finale fanno di questo vino un prodotto ideale per accompagnare pranzi a base di carne o pesce, e risulta particolarmente adatto ad un dessert.",12.5,"vino","56.jpg");
INSERT INTO product values (57,"VERDICCHIO DEI CASTELLI DI JESI CLASSICO SUPERIORE DOC 2020",18.90,"Il Verdicchio dei Castelli di Jesi di Villa Bucci è un vino bianco secco prodotto con Verdicchio in purezza nelle Marche, nella zona Classica dei Castelli di Jesi. Il patron di questa storica cantina, Ampelio Bucci, è stato una figura chiave per la rivalutazione del Verdicchio, di cui ha dimostrato l’enorme potenziale. I vini di Ampelio sono apprezzati e ricercati in tutto il mondo per il loro indiscusso livello qualitativo e la capacità evolutiva.",14,"vino","57.jpg");
INSERT INTO product values (58,"RENOSU BIANCO 2020",12.90,"Il Renosu Bianco prodotto dalle cantine sarde Dettori è un vino di grande complessità. Al palato è particolarmente fruttato e accanto ai sentori di frutta matura presenta sapori speziati e di erbe aromatiche. Assaporarlo e sentirne i profumi assicura un'esperienza sensoriale senza eguali. In bocca, infatti, questo bianco si caratterizza per le sue note dolci e per il suo straordinario finale tendente al sapido. Esprime una singolare tonalità oro ramato, chiara e brillante. Fini e fragranti i richiami di pera matura, pesca tabacchiera, fiori bianchi, finocchietto e macchia mediterranea, combinati a cenni di pasticceria reminiscenti di burro e cannella. Il tutto è sostenuto da nitide sensazioni di mare, in un contesto dolce e minerale. Il sorso è avvolgente, morbido e slanciato al contempo, dalla gradevole scia sapida che accompagna il finale mielato e floreale. Espressione pura ed estremamente piacevole, di grande armonia.",13,"vino","58.jpg");
INSERT INTO product values (59,"PRADALUPO ROERO ARNEIS DOCG 2021",13.90,"Il Roero Arneis 'Pradalupo Le Righe', della storica cantina piemontese Fontanafredda, è un bianco fresco, fragrante e fruttato, di grande piacevolezza di beva, giovane e immediato. La bottiglia fa parte di una collezione, che nella grafica dell’etichetta, riprende le righe orizzontali caratteristiche degli edifici dell’antico borgo di Fontanafredda. Il Roero Arneis è un vino bianco morbido e profumato, in cui acidità e dolcezza si bilanciano magnificamente. I riflessi verdi accendono il giallo paglierino di questo vino bianco che può essere servito praticamente a tutto pasto: fresco è infatti un ottimo aperitivo, si abbina magnificamente con piatti di pesce, primi piatti leggeri e anche con il classico vitello tonnato tipico della cucina piemontese. Al naso sprigiona sentori di frutta esotica, miele d'acacia e pera, che si uniscono a quelli dei fiori di biancospino in un bouquet molto ricco.",14,"vino","59.jpg");
INSERT INTO product values (60,"SAUVIGNON WINKL 2018",37.90,"Tra le colline che si estendono ai piedi delle maestose Alpi altoatesine nasce il Sauvignon Blanc ‘Winkl’ di Cantina Terlano, un’etichetta che ben riflette la caratteristica freschezza e mineralità donate sia dal vitigno sia dal territorio. Fin dal lontano 1956 la celebre realtà vitivinicola Cantina Terlano vinifica il Sauvignon Blanc in purezza e nel tempo è riuscita a conoscere e padroneggiare questa varietà raggiungendo altissimi livelli qualitativi e configurandosi come una delle massime interpreti in Italia. Il Sauvignon Winkl Terlano è un'etichetta storica del territorio trentino che riuscirà ad allietare la tua giornata. Di un intenso colore giallo paglierino, il suo bouquet lascia trasparire note fruttate di albicocca, elicriso e sambuco. Al palato il Sauvignon Winkl Terlano si presenta fruttato, con un leggero retrogusto acido e minerale che va a completarne il sapore Si tratta di un vino equilibrato e versatile, che potrai accompagnare a diversi piatti.",13.5,"vino","60.jpg");


INSERT INTO utente values ('prova','prova','prova','prova','2000-01-01','admin');
INSERT INTO utente values ('user','user','user','user','2000-01-01','user');
INSERT INTO utente values ('admin','admin','admin','admin','2000-01-01','admin');
